version: "3.7"
services:
   backend:
     build: ./backend
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./backend:/src
     ports:
       - "8000:8000"
     container_name: backend
   frontend:
     build: ./frontend
     volumes:
       - ./frontend:/frontend
     expose:
       - "3000"
     container_name: frontend
   nginx-proxy:
     build: ./
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf:ro
     ports:
       - "80:80"
     container_name: nginx-proxy
