# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    # Runs backend tests
    - name: Backend-tests
      run: | 
          cd Solan/backend
          sudo -H pip3 install --upgrade pip
          pip3 --version
          pip install Django djangorestframework Pillow django-cors-headers requests oic
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

    # Runs frontend tests
    - name: Frontend-tests
      run: |
        cd Solan/frontend
        npm install
        npm test
        a
